### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by kukv** [kukv/kULID#11]
Mainly a list of tasks to be worked on in the future.

- [ ] Switch to multi-platform
- [ ] Fixed problem with broken encoding of entropy
- [ ] Isolate the source of the components of the ULID
- [ ] Monotonicity support (as it doesn't seem to be there from a quick glance at the source)
